language: android
sudo: required
dist: precise
android:
  components:
    - build-tools-28.0.2
    - android-28
  script:
    - ./gradlew assembleRelease
  after_script:
    - ./gradlew crashlyticsUploadDistributionRelease