language: android

android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.2
    - android-28
  licenses:
    - android-sdk-preview-license-c81a61d9
    - android-sdk-license-.+
    branches:
      only:
        - master
  after_script:
    - ./gradlew crashlyticsUploadDistributionRelease