language: android
jdk: oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.2
    - android-28
    - extra-android-m2repository
    - extra-google-google_play_services
    - extra-google-m2repository
  script:
    - ./gradlew assembleRelease
  after_script:
    - ./gradlew crashlyticsUploadDistributionRelease