language: android

  android:

    components:
      - build-tools-28.0.2
      - android-28
      - sys-img-armeabi-v7a-android-22
      - add-on
      - extra

    licenses:
      - 'android-sdk-preview-license-52d11cd2'
      - 'android-sdk-license-.+'