language: android
sudo: required
dist: precise
android:
  components:
    - build-tools-28.0.2
    - android-28
  licenses:
    - android-sdk-preview-license-c81a61d9
    - android-sdk-license-.+
    - google-gdk-license-.+
  script:
    - ./gradlew assembleRelease
  after_script:
    - ./gradlew crashlyticsUploadDistributionRelease